<a href="https://colab.research.google.com/github/PDachu/Python-Data-sicence/blob/main/Pandas_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

A series  is a one dimensional labelled data stucture

Pandas Series = one-dimensional labelled data structure containing values and an index

In [ ]:
marks =pd.Series([80 ,75,90,85])

In [ ]:
print(marks)

0    80
1    75
2    90
3    85
dtype: int64

80, 75, 90, 85 → values
0, 1, 2, 3 → labels/index
It is one-dimensional → like a single column of data. we can also create our own custom labels and index

In [ ]:
marks = pd.Series ([80 ,90, 95],
index = ["john","Rahul","ramu"])

In [ ]:
print(marks)

john     80
Rahul    90
ramu     95
dtype: int64

Data Frame
A DataFrame is a two-dimensional table containing rows and columns.

In [ ]:
data = {
    "Name": [
        "John",
        "Anu",
        "Rahul"
    ],

    "Age": [
        22,
        21,
        23
    ],

    "Marks": [
        85,
        90,
        78
    ]
}

(data)

{'Name': ['John', 'Anu', 'Rahul'], 'Age': [22, 21, 23], 'Marks': [85, 90, 78]}

In [ ]:
df = pd.DataFrame(data)
df

    Name  Age  Marks
0   John   22     85
1    Anu   21     90
2  Rahul   23     78

In [ ]:
df

    Name  Age  Marks
0   John   22     85
1    Anu   21     90
2  Rahul   23     78

dont use print if yiu want table use only df or dataframe function so it will be in a table format

In [ ]:
df.head(4)

    Name  Age  Marks
0   John   22     85
1    Anu   21     90
2  Rahul   23     78

isin() is used to filter rows where a column value matches any value from a given list

In [ ]:
df[
    df["Name"].isin(
        ["John", "Anu"]
    )
]

   Name  Age  Marks
0  John   22     85
1   Anu   21     90

In [ ]:
df = df.rename(
    columns={
        "Marks": "Score"
    }
)

In [ ]:
df[
    df["Name"].isin(
        ["John", "Anu"]
    )
]

   Name  Age  Marks
0  John   22     85
1   Anu   21     90